### ISSUE TITLE
iPhone 7 plus 10.3.2 stuck at "updating baseband in progress..."

### ISSUE THREAD

**Issue by seiterseiter** [encounter/futurerestore#1]
The title says it all really, Everything seems to have gone alright until it his updating baseband and just got stuck and I dont really want to restart my iPhone cause it will most likely bootloop.

error code below: 

G:\Desktop\Upgrade>futurerestore.exe -t G:\Desktop\Upgrade\blob.shsh2 --latest-baseband --latest-sep G:\Desktop\Upgrade\7plus11_1_2.ipsw
Version: 15fcc8849c526d55f8bcfe4c18e20b27ac1cd62a - 161
Odysseus Support: no
[INFO] 64bit device detected
futurerestore init done
reading ticket G:\Desktop\Upgrade\blob.shsh2 done
Found device product iPhone9,4
Found device board d111ap
user specified to use latest signed sep
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
Found device product iPhone9,4
[TSSC] selecting latest iOS: 11.2.1
[TSSC] got firmwareurl for iOS 11.2.1 build 15C153
100 [===================================================================================================>]
downloading SEP
100 [===================================================================================================>]
[TSSC] opening download/sepManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
user specified to use latest signed baseband (WARNING, THIS CAN CAUSE A NON-WORKING RESTORE)
downloading Baseband
100 [===================================================================================================>]
[TSSC] opening download/basebandManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is F2LSHS8QHFYD
Found device in Recovery mode
Identified device as d111ap, iPhone9,4
Extracting BuildManifest from IPSW
Product Version: 11.1.2
Product Build: 15B202 Major: 15
Device supports Image4: true
Got APNonce from device: 65 fc 1f 4f 6f ce c8 ea b4 3a af a8 70 b7 a3 5a df cb 71 b4 9b 81 83 9a 2a 00 88 b5 08 b9 84 da
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Extracting filesystem from IPSW
Extracting iBEC.d11.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (422709 bytes)...
waiting for device to reconnect...
Getting SepNonce in recovery mode... df d3 38 5f d9 ab a7 93 1f 66 2d c8 e2 b8 f3 27 6e a4 29 c1
Getting ApNonce in recovery mode... 65 fc 1f 4f 6f ce c8 ea b4 3a af a8 70 b7 a3 5a df cb 71 b4 9b 81 83 9a 2a 00 88 b5 08 b9 84 da
[WARNING] Setting bgcolor to green! If you don't see a green screen, then your device didn't boot iBEC correctly
Recovery Mode Environment:
iBoot build-version=iBoot-4076.20.48
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@3x~iphone.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (19538 bytes)...
ramdisk-size=0x20000000
Extracting 058-84556-102.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (59136179 bytes)...
Extracting DeviceTree.d111ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (153469 bytes)...
Extracting kernelcache.release.iphone9...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (15237709 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device...
Waiting for device...
Device ffffffffffffffffffffffffffffffff00000008 is now connected in restore mode...
Connecting now...
Connected to com.apple.mobile.restored, version 15
Device ffffffffffffffffffffffffffffffff00000008 has successfully entered restore mode
Hardware Information:
BoardID: 14
ChipID: 32784
UniqueChipID: 6304170595454246
ProductionMode: true
Starting FDR listener thread
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.d11.RELEASE.im4p...
Personalizing IMG4 component LLB...
Extracting applelogo@3x~iphone.im4p...
Personalizing IMG4 component AppleLogo...
Extracting batterycharging0@3x~iphone.im4p...
Personalizing IMG4 component BatteryCharging0...
Extracting batterycharging1@3x~iphone.im4p...
Personalizing IMG4 component BatteryCharging1...
Extracting batteryfull@3x~iphone.im4p...
Personalizing IMG4 component BatteryFull...
Extracting batterylow0@3x~iphone.im4p...
Personalizing IMG4 component BatteryLow0...
Extracting batterylow1@3x~iphone.im4p...
Personalizing IMG4 component BatteryLow1...
Extracting glyphplugin@1920~iphone-lightning.im4p...
Personalizing IMG4 component BatteryPlugin...
Extracting DeviceTree.d111ap.im4p...
Personalizing IMG4 component DeviceTree...
Extracting liquiddetect@1920~iphone-lightning.im4p...
Personalizing IMG4 component Liquid...
Extracting recoverymode@1920~iphone-lightning.im4p...
Personalizing IMG4 component RecoveryMode...
Extracting iBoot.d11.RELEASE.im4p...
Personalizing IMG4 component iBoot...
Personalizing IMG4 component RestoreSEP...
Personalizing IMG4 component SEP...
Sending NORData now...
Done sending NORData
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Waiting for NAND (28)
Updating S3E Firmware (58)
Checking filesystems (15)
Checking filesystems (15)
About to send FDR Trust data...
Sending FDR Trust data now...
Done sending FDR Trust Data
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Creating partition map (11)
Creating filesystem (12)
About to send filesystem...
Connected to ASR
Validating the filesystem
Filesystem validated
Sending filesystem now...
Done sending filesystem
Verifying restore (14)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
Mounting filesystems (16)
Mounting filesystems (16)
Mounting filesystems (16)
About to send KernelCache...
Extracting kernelcache.release.iphone9...
Personalizing IMG4 component KernelCache...
Sending KernelCache now...
Done sending KernelCache
Installing kernelcache (27)
About to send DeviceTree...
Extracting DeviceTree.d111ap.im4p...
Personalizing IMG4 component DeviceTree...
Sending DeviceTree now...
Done sending DeviceTree
Certifying Savage (61)
Flashing firmware (18)
Updating gas gauge software (47)
Updating gas gauge software (47)
Updating Stockholm (55)
About to send FUD data...
Found FUD component 'AOP'
Extracting aopfw-t8010aop.im4p...
Personalizing IMG4 component AOP...
Found FUD component 'Homer'
Extracting homer_D111.im4p...
Personalizing IMG4 component Homer...
Sending FUD data now...
Done sending FUD data
About to send FUD data...
Found FUD component 'AOP'
Extracting aopfw-t8010aop.im4p...
Personalizing IMG4 component AOP...
Found FUD component 'Homer'
Extracting homer_D111.im4p...
Personalizing IMG4 component Homer...
Sending FUD data now...
Done sending FUD data
Updating baseband (19)
About to send BasebandData...
WARNING: Unable to find BbSkeyId node
Sending Baseband TSS request...
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received Baseband SHSH blobs
Sending BasebandData now...
Done sending BasebandData
Updating Baseband in progress...

**Comment by encounter** [comment]
It takes a bit for the baseband update, probably no more than 5 minutes... maybe the USB connection reset during the process? Did you end up stopping it?

**Comment by seiterseiter** [comment]
@encounter Yeah I did stop it and put my iPhone into a bootloop.. So in other words I had to restore..

**Comment by encounter** [comment]
Sorry about that. While unfortunate, I think this was a fluke. I haven't seen any other reports like this yet, and multiple success reports from other iPhone9,4 users. I'm going to close this for now.
