### ISSUE TITLE
what should i do, it can't find correct code

### ISSUE THREAD

**Issue by yeuhetminh24** [encounter/futurerestore#10]
![image](https://user-images.githubusercontent.com/35330073/34818239-d3e89dce-f6ec-11e7-8606-37202987bd08.png)
iphone 6s 11.2.1 to 10.3.2

**Comment by encounter** [comment]
don't use -w, and set the nonce before running the tool. look up a tutorial. also you can't downgrade to ios 10.x on the 6s, since only ios 11 baseband/sep is signed, and is incompatible with ios 10.
