### ISSUE TITLE
[iPhone 9,4] Unable to get into recovery mode

### ISSUE THREAD

**Issue by antonioag95** [encounter/futurerestore#2]
After issuing the command on Mac OS High Sierra 10.3.2, my iPhone 7 Plus GSM (iPhone9,4) on iOS 10.3.1 does not get into recovery mode. It just reboots in normal mode. From terminal I can see it says:

    Entering recovery mode...

And after a while:

    ERROR: Unable to enter recovery mode
    ERROR: Unable to place device into recovery mode from Normal mode

I've already installed all the necessary libraries through Brew.

**Comment by maxvibration** [comment]
Got the same issue but with iPhone 9,3, tried it on different Systems, Windows10, High Sierra VM and High Sierra on MBPro. I'm not sure if it's a futurerestore Problem cause after setting my boot-nonce with v0rtexnonce i also can't get into recovery mode with holding Power+Vol Down or the tool ReiBoot.

**Comment by antonioag95** [comment]
After reading what @maxvibration wrote I tried if I could get into recovery mode using ReiBoot with the nonce set and...I couldn't. To be sure, I rebooted the iPhone, I did NOT set the nonce and I could get into recovery mode without any problem. So I guess you're right, it's all about v0rtexNonce, so I opened an issue there, you can write about your problem there too, if you want.

**Comment by encounter** [comment]
Interesting. I'm wondering if v0rtexNonce may affect permissions for the auto-boot nvram variable. I'll keep this open until it's resolved.

**Comment by antonioag95** [comment]
@arx8x helped me figuring out the problem I was facing. It seems that some devices need to be powered-off and then powered-on before they can be placed into recovery mode. I confirm that the nonce set by v0rtexNonce is kept also after a reboot. To be sure that the correct nonce is written on the phone, write "-w" in terminal while using futurerestore.
Thank you for your interest, @encounter.

**Comment by encounter** [comment]
Cool. So v0rtexNonce -> reboot -> let futurerestore place it in recovery?

The -w flag is only for nonce collision. By default it will stop the process if the nonce does not match.

**Comment by antonioag95** [comment]
It worked exactly as you described. So...problem solved :+1:
