### ISSUE TITLE
Argument parsing failed

### ISSUE THREAD

**Issue by neerajvohra** [encounter/futurerestore#25]
I've seen many reports for this error and searched with no solution. I'm trying to restore iPhone 6S Plus from 10.2 to 11.1.2 with valid blobs. During the command I see this error even when the device is not in recovery. I managed to reboot back from recovery via ReiBoot. Any help to fix this please?

C:\Users\Neeraj\Desktop\futurerestore>futurerestore -t blob.shsh2 --latest-sep -
latest-baseband iPhone_5.5_11.1.2_15B202_Restore.ipsw
Version: a0113a4e46bfd00962cd25e3af548fc8b0bd21fd - 173
Odysseus Support: no
[Error] argument parsing failed! agrc=6 optind=2

**Comment by encounter** [comment]
it just means your arguments are wrong... add another dash to make it --latest-baseband

**Comment by neerajvohra** [comment]
You beauty! @encounter Thank you so much. 

Modifying persistent boot-args (25)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Got status message
Status: Restore Finished
Cleaning up...
DONE
Done: restoring succeeded.
