### ISSUE TITLE
Errorcode=-11 while running on iPhone6S+, iOS 10.2 on windows

### ISSUE THREAD

**Issue by kskumar9663** [encounter/futurerestore#28]
I am getting below error while running futurerestore on windows 10

Received SHSH blobs
About to restore device...
Waiting for device...
Attempt 1 to connect to restore mode device...
Attempt 2 to connect to restore mode device...
Attempt 3 to connect to restore mode device...
Attempt 4 to connect to restore mode device...
Attempt 5 to connect to restore mode device...
Attempt 6 to connect to restore mode device...
Attempt 7 to connect to restore mode device...
Attempt 8 to connect to restore mode device...
Attempt 9 to connect to restore mode device...
Attempt 10 to connect to restore mode device...
Attempt 11 to connect to restore mode device...
Attempt 12 to connect to restore mode device...
Attempt 13 to connect to restore mode device...
Attempt 14 to connect to restore mode device...
Attempt 15 to connect to restore mode device...
Attempt 16 to connect to restore mode device...
Attempt 17 to connect to restore mode device...
Attempt 18 to connect to restore mode device...
Attempt 19 to connect to restore mode device...
Attempt 20 to connect to restore mode device...
Attempt 21 to connect to restore mode device...
Attempt 22 to connect to restore mode device...
Attempt 23 to connect to restore mode device...
Attempt 24 to connect to restore mode device...
Attempt 25 to connect to restore mode device...
Attempt 26 to connect to restore mode device...
Attempt 27 to connect to restore mode device...
Attempt 28 to connect to restore mode device...
Attempt 29 to connect to restore mode device...
Attempt 30 to connect to restore mode device...
Attempt 31 to connect to restore mode device...
Attempt 32 to connect to restore mode device...
Attempt 33 to connect to restore mode device...
Attempt 34 to connect to restore mode device...
Attempt 35 to connect to restore mode device...
Attempt 36 to connect to restore mode device...
Attempt 37 to connect to restore mode device...
Attempt 38 to connect to restore mode device...
Attempt 39 to connect to restore mode device...
Attempt 40 to connect to restore mode device...
Attempt 41 to connect to restore mode device...
Attempt 42 to connect to restore mode device...
Attempt 43 to connect to restore mode device...
Attempt 44 to connect to restore mode device...
Attempt 45 to connect to restore mode device...
Attempt 46 to connect to restore mode device...
Attempt 47 to connect to restore mode device...
Attempt 48 to connect to restore mode device...
Attempt 49 to connect to restore mode device...
Attempt 50 to connect to restore mode device...
Attempt 51 to connect to restore mode device...
Attempt 52 to connect to restore mode device...
Attempt 53 to connect to restore mode device...
Attempt 54 to connect to restore mode device...
Attempt 55 to connect to restore mode device...
Attempt 56 to connect to restore mode device...
Attempt 57 to connect to restore mode device...
Attempt 58 to connect to restore mode device...
Attempt 59 to connect to restore mode device...
Attempt 60 to connect to restore mode device...
Attempt 61 to connect to restore mode device...
Attempt 62 to connect to restore mode device...
Attempt 63 to connect to restore mode device...
Attempt 64 to connect to restore mode device...
Attempt 65 to connect to restore mode device...
Attempt 66 to connect to restore mode device...
Attempt 67 to connect to restore mode device...
Attempt 68 to connect to restore mode device...
Attempt 69 to connect to restore mode device...
Attempt 70 to connect to restore mode device...
Attempt 71 to connect to restore mode device...
Attempt 72 to connect to restore mode device...
Attempt 73 to connect to restore mode device...
Attempt 74 to connect to restore mode device...
Attempt 75 to connect to restore mode device...
Attempt 76 to connect to restore mode device...
Attempt 77 to connect to restore mode device...
Attempt 78 to connect to restore mode device...
Attempt 79 to connect to restore mode device...
Attempt 80 to connect to restore mode device...
Attempt 81 to connect to restore mode device...
Attempt 82 to connect to restore mode device...
Attempt 83 to connect to restore mode device...
Attempt 84 to connect to restore mode device...
Attempt 85 to connect to restore mode device...
Attempt 86 to connect to restore mode device...
Attempt 87 to connect to restore mode device...
Attempt 88 to connect to restore mode device...
Attempt 89 to connect to restore mode device...
Attempt 90 to connect to restore mode device...
Attempt 91 to connect to restore mode device...
Attempt 92 to connect to restore mode device...
Attempt 93 to connect to restore mode device...
Attempt 94 to connect to restore mode device...
Attempt 95 to connect to restore mode device...
Attempt 96 to connect to restore mode device...
Attempt 97 to connect to restore mode device...
Attempt 98 to connect to restore mode device...
Attempt 99 to connect to restore mode device...
Attempt 100 to connect to restore mode device...
Attempt 101 to connect to restore mode device...
Attempt 102 to connect to restore mode device...
Attempt 103 to connect to restore mode device...
Attempt 104 to connect to restore mode device...
Attempt 105 to connect to restore mode device...
Attempt 106 to connect to restore mode device...
Attempt 107 to connect to restore mode device...
Attempt 108 to connect to restore mode device...
Attempt 109 to connect to restore mode device...
Attempt 110 to connect to restore mode device...
Attempt 111 to connect to restore mode device...
Attempt 112 to connect to restore mode device...
Attempt 113 to connect to restore mode device...
Attempt 114 to connect to restore mode device...
Attempt 115 to connect to restore mode device...
Attempt 116 to connect to restore mode device...
Attempt 117 to connect to restore mode device...
Attempt 118 to connect to restore mode device...
Attempt 119 to connect to restore mode device...
Attempt 120 to connect to restore mode device...
Attempt 121 to connect to restore mode device...
Attempt 122 to connect to restore mode device...
Attempt 123 to connect to restore mode device...
Attempt 124 to connect to restore mode device...
Attempt 125 to connect to restore mode device...
Attempt 126 to connect to restore mode device...
Attempt 127 to connect to restore mode device...
Attempt 128 to connect to restore mode device...
Attempt 129 to connect to restore mode device...
Attempt 130 to connect to restore mode device...
Attempt 131 to connect to restore mode device...
Attempt 132 to connect to restore mode device...
Attempt 133 to connect to restore mode device...
Attempt 134 to connect to restore mode device...
Attempt 135 to connect to restore mode device...
Attempt 136 to connect to restore mode device...
Attempt 137 to connect to restore mode device...
Attempt 138 to connect to restore mode device...
Attempt 139 to connect to restore mode device...
Attempt 140 to connect to restore mode device...
Attempt 141 to connect to restore mode device...
Attempt 142 to connect to restore mode device...
Attempt 143 to connect to restore mode device...
Attempt 144 to connect to restore mode device...
Attempt 145 to connect to restore mode device...
Attempt 146 to connect to restore mode device...
Attempt 147 to connect to restore mode device...
Attempt 148 to connect to restore mode device...
Attempt 149 to connect to restore mode device...
Attempt 150 to connect to restore mode device...
Attempt 151 to connect to restore mode device...
Attempt 152 to connect to restore mode device...
Attempt 153 to connect to restore mode device...
Attempt 154 to connect to restore mode device...
Attempt 155 to connect to restore mode device...
Attempt 156 to connect to restore mode device...
Attempt 157 to connect to restore mode device...
Attempt 158 to connect to restore mode device...
Attempt 159 to connect to restore mode device...
Attempt 160 to connect to restore mode device...
Attempt 161 to connect to restore mode device...
Attempt 162 to connect to restore mode device...
Attempt 163 to connect to restore mode device...
Attempt 164 to connect to restore mode device...
Attempt 165 to connect to restore mode device...
Attempt 166 to connect to restore mode device...
Attempt 167 to connect to restore mode device...
Attempt 168 to connect to restore mode device...
Attempt 169 to connect to restore mode device...
Attempt 170 to connect to restore mode device...
Attempt 171 to connect to restore mode device...
Attempt 172 to connect to restore mode device...
Attempt 173 to connect to restore mode device...
Attempt 174 to connect to restore mode device...
Attempt 175 to connect to restore mode device...
Attempt 176 to connect to restore mode device...
Attempt 177 to connect to restore mode device...
Attempt 178 to connect to restore mode device...
Attempt 179 to connect to restore mode device...
Attempt 180 to connect to restore mode device...
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

**Comment by encounter** [comment]
try a different USB port

**Comment by kskumar9663** [comment]
Thank you. I changed the USB but got the same error. Tried with another USB & new cable. This time it passed the reported phase. Thanks for the info. Appreciate it.
