### ISSUE TITLE
Am I dumb?

### ISSUE THREAD

**Issue by simsdj** [encounter/futurerestore#3]
I set the generator with noncesetter1112 and when I start the restore process is says it's waiting for the correct nonce. But when it reboots the nonce is wrong. Is this futurerestore or is it my fault?

**Comment by encounter** [comment]
I'd avoid using the -w flag, which is for nonce collision. It's possible you typed the nonce wrong? Double check the generator in your SHSH file.

**Comment by simsdj** [comment]
is there anyway I can talk to you directly?

**Comment by encounter** [comment]
Is the nonce that futurerestore prints out at all similar to the one you're trying to set? If not it sounds like it could be a NonceSet1112 issue.

**Comment by simsdj** [comment]
This is the nonce it's waiting for: 11 54 b2 4d c1 05 65 c6 2b 31 29 a4 e4 5e 71 6b ba e1 2f d5
This is the nonce and the only nonce it prints out: 
25 b9 5d d9 0b e9 d7 9a 83 b8 16 a9 03 09 b0 68 d1 7b 9d c3 d4 fb 88 4d 88 38 b0 aa 25 59 e8 70

Could it be that different because I'm on an iPhone X?

**Comment by encounter** [comment]
So iPhone10,x uses a 32 byte nonce. Interesting! Could you send me your SHSH file either here or on Reddit (/u/firstEncounter) and I can take a look.

**Comment by simsdj** [comment]
https://www.dropbox.com/s/62zbycfitfxetgv/iPhone10%2C3_d22ap_11.1.2-15B202.shsh2?dl=0

**Comment by billkenney** [comment]
I attempted to restore my iPad Pro 9.7 from 10.3.2 to 11.1.2 yesterday (twice) with v157 on OS X, and both times the following was returned: `[INFO] 32bit device detected`.  I successfully set the nonce with v0rtexnonce (using uroboro's find_offsets.sh script to get the offsets), but the above error was returned each time I tried to restore. I'm hesitant to try again because I somehow bricked my iPad mini 2 trying to go from 9.3.3 to 10.2.1. 
Here's the terminal command I used:
`./futurerestore_macos -t blob.shsh2 --latest-sep --no-baseband iPadPro_9.7_11.1.2_15B202_Restore.ipsw`
Here's my [shsh2 blob](https://www.dropbox.com/s/2yf8uuc3ug7ccn6/1693377435779622_iPad6%2C3_j127ap_11.1.2-15B202_dbce149ae22da3bb51003fe973ea18fc5fd37df7.shsh2?dl=0)
Thanks for your work on this btw 👍

**Comment by encounter** [comment]
@billkenney That's usually accompanied with a "couldn't connect to device" error. Try plugging in the device while it's unlocked.

**Comment by simsdj** [comment]
Have you found anything with my blobs?

**Comment by encounter** [comment]
I believe all SHSH blobs saved for iPhone 8 and X so far are invalid. I'll be releasing an updated tsschecker/img4tool that properly supports them.

**Comment by simsdj** [comment]
so the blobs are useless? or will they work once you release those?

**Comment by encounter** [comment]
Looks like they're useless as they've been saving with a 20 byte nonce, unfortunately.

**Comment by simsdj** [comment]
I wanted to restore because my phone has that nasty respring bug going on. But i've also used a lot of the async forks. Do you think its the bug that 11.2 patched or could it be the async forks?

**Comment by billkenney** [comment]
@encounter - You were correct. I was able to upgrade the iPad Pro successfully to 11.1.2

**Comment by simsdj** [comment]
so is it not possible to restore 11.1.2 to 11.1.2?

**Comment by encounter** [comment]
@billkenney Great!

@simsdj No, not right now.

**Comment by simsdj** [comment]
dang. looks like i have to update then. Thanks anyway for trying

**Comment by encounter** [comment]
A possible solution for restoring to your current firmware was brought up in #4, so don't restore just yet!

**Comment by vidnotes** [comment]
As simsdj had problem with Iphone X also iPad Pro (10.5-inch) needs 32 bytes nonce:

futurerestore_v161_windows>futurerestore.exe -w -t ticket.shsh2 -u --latest-sep --no-baseband iPad_Pro_HFR_11.1.2_15B202_Restore.ipsw
..
waiting for nonce: b8 26 e7 a0 43 c3 62 0c 26 67 52 04 78 4c f5 76 71 ce c9 7d
Got ApNonce from device: e5 29 ce 4d c1 fb d6 ce d3 16 4a 02 c3 1c 71 27 ae d7 36 2b 3b e3 d8 f3 cb 56 7f 8b 6d ad ff 4f
Got ApNonce from device: e5 29 ce 4d c1 fb d6 ce d3 16 4a 02 c3 1c 71 27 ae d7 36 2b 3b e3 d8 f3 cb 56 7f 8b 6d ad ff 4f
Got ApNonce from device: e5 29 ce 4d c1 fb d6 ce d3 16 4a 02 c3 1c 71 27 ae d7 36 2b 3b e3 d8 f3 cb 56 7f 8b 6d ad ff 4f
