### ISSUE TITLE
Unable to receive message from FDR 0x7fd539d6db30 (11.0.3 -> 11.2.6 w/ 11.3 sep)

### ISSUE THREAD

**Issue by kasiimh1** [encounter/futurerestore#36]
WARNING: user specified not to flash a baseband. This can make the restore fail if the device needs a baseband!
if you added this flag by mistake you can press CTRL-C now to cancel
continuing restore in 5 4 3 2 1 ^[[A
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is 
waiting for nonce: cc 12 be e9 75 e5 22 d3 e8 15 87 6e 36 f5 e4 94 25 67 bb 30 
Got ApNonce from device: cc 12 be e9 75 e5 22 d3 e8 15 87 6e 36 f5 e4 94 25 67 bb 30 
Device has requested ApNonce now
Found device in Recovery mode
Identified device as j81ap, iPad5,3
Extracting BuildManifest from IPSW
Product Version: 11.2.6
Product Build: 15D100 Major: 15
Device supports Image4: true
Got APNonce from device: cc 12 be e9 75 e5 22 d3 e8 15 87 6e 36 f5 e4 94 25 67 bb 30 
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Extracting filesystem from IPSW
[==================================================] 100.0%
Extracting iBEC.ipad5b.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (706741 bytes)...
waiting for device to reconnect... 
Getting SepNonce in recovery mode... 8f 3a 11 7b 02 e9 be 3b b7 9c 25 7e 21 91 25 86 d5 3b 40 30 
Getting ApNonce in recovery mode... cc 12 be e9 75 e5 22 d3 e8 15 87 6e 36 f5 e4 94 25 67 bb 30 
[WARNING] Setting bgcolor to green! If you don't see a green screen, then your device didn't boot iBEC correctly
Recovery Mode Environment:
iBoot build-version=iBoot-4076.30.43
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~ipad.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (23186 bytes)...
ramdisk-size=0x20000000
Extracting 058-94922-067.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (59266547 bytes)...
Extracting DeviceTree.j81ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (118220 bytes)...
Extracting kernelcache.release.ipad5b...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (13996264 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbChipID node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Waiting for device...
Device 1ccb19cd9d85621b27d21c2c361a1bfe41ba86d0 is now connected in restore mode...
Connecting now...
Connected to com.apple.mobile.restored, version 15
Device 1ccb19cd9d85621b27d21c2c361a1bfe41ba86d0 has successfully entered restore mode
Hardware Information:
BoardID: 6
ChipID: 28673
UniqueChipID: 7425707016202278
ProductionMode: true
Starting FDR listener thread
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.ipad5b.RELEASE.im4p...
Personalizing IMG4 component LLB...
Extracting applelogo@2x~ipad.im4p...
Personalizing IMG4 component AppleLogo...
Extracting batterycharging0@2x~ipad.im4p...
Personalizing IMG4 component BatteryCharging0...
Extracting batterycharging1@2x~ipad.im4p...
Personalizing IMG4 component BatteryCharging1...
Extracting batteryfull@2x~ipad.im4p...
Personalizing IMG4 component BatteryFull...
Extracting batterylow0@2x~ipad.im4p...
Personalizing IMG4 component BatteryLow0...
Extracting batterylow1@2x~ipad.im4p...
Personalizing IMG4 component BatteryLow1...
Extracting glyphplugin@2x~ipad-lightning.im4p...
Personalizing IMG4 component BatteryPlugin...
Extracting DeviceTree.j81ap.im4p...
Personalizing IMG4 component DeviceTree...
Extracting recoverymode@2x~ipad-lightning.im4p...
Personalizing IMG4 component RecoveryMode...
Extracting iBoot.ipad5b.RELEASE.im4p...
Personalizing IMG4 component iBoot...
Personalizing IMG4 component RestoreSEP...
Personalizing IMG4 component SEP...
Sending NORData now...
Done sending NORData
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Waiting for NAND (28)
Checking filesystems (15)

ERROR: Unable to receive message from FDR 0x7fd539d6db30 (-4). 0/2 bytes

**Comment by ProAppleOS** [comment]
Ignore that error. It should go on

**Comment by encounter** [comment]
11.3 SEP is incompatible with 11.2.6.

**Comment by kasiimh1** [comment]
Nope it fails and goes into recovery mode, it's fine I knew it wasn't but wanted to check in case something magical happened. As I wanted to restore it to 11.3 as performance was really bad on 11.0.3, will close. Thanks!
