### ISSUE TITLE
[Error] Fail code=-2 | [Error] Unable to place device into recovery mode from Normal mode

### ISSUE THREAD

**Issue by alexethan** [encounter/futurerestore#39]
Found device in Normal mode
Entering recovery mode...
ERROR: Unable to connect to device in recovery mode
ERROR: Unable to enter recovery mode
[Error] Unable to place device into recovery mode from Normal mode
[Error] Fail code=-2
Failed with errorcode=-2

My device has entered the recovery mode and has tried to replace the USB interface, which is still invalid.

iPhone X 11.3(beta 6) | Windows | Version :v173

**Comment by ZEN1X** [comment]
After setting the nonce, boot into recovery either manually or using ReiBoot.

How to do it manually:
Press and quickly release the Volume Up button. Press and quickly release the Volume Down button. Then, press and hold the Side button until you see the connect to iTunes screen.
