### ISSUE TITLE
Can't restore iPhone 8 Plus (Intel)

### ISSUE THREAD

**Issue by nnvt** [encounter/futurerestore#4]
Hi!

I can't seem to restore my iPhone 8 Plus (with Intel modem) using futurerestore, it shows this after downloading the baseband:

[TSSC] opening /tmp/futurerestore/basebandManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
TSS server returned: STATUS=132&MESSAGE=An internal error occurred.
ERROR: tss_send_request: Unhandled status code 132
Sending TSS request attempt 1... Request URL set to https://17.171.36.30/TSS/controller?action=2
ERROR: tss_send_request: Unhandled status code 132
Sending TSS request attempt 2... Request URL set to https://17.151.36.30/TSS/controller?action=2

And it keeps going

Any ideas?

**Comment by encounter** [comment]
This will be fixed in an upcoming release.

**Comment by nnvt** [comment]
Awesome! One question though: since all currently saved blobs for the iPhone 8 and X are invalid, can I restore to my current firmware with just the apticket.der? I’ve already converted it to shsh and got the generator from img4tool.

**Comment by encounter** [comment]
I wasn't aware of apticket.der until now, that's interesting. I'd verify the SHSH using the img4tool update I just released, if that succeeds then I'm guessing it'd work (with a 11.2(.1) SEP/baseband of course).

**Comment by simsdj** [comment]
the recent release doesnt work for me

**Comment by encounter** [comment]
of img4tool? or what?

**Comment by simsdj** [comment]
img4tool. the build fails

**Comment by simsdj** [comment]
wait i just saw the release

**Comment by simsdj** [comment]
how do i convert the .der to shsh

**Comment by encounter** [comment]
I haven't tried it, but I think like this: ```img4tool --convert -s out.shsh apticket.der```

**Comment by simsdj** [comment]
ok time to see if this works

**Comment by simsdj** [comment]
the generator key isn't there

**Comment by encounter** [comment]
Yep, just looked into it more, and it's not usable without knowing the generator.

**Comment by simsdj** [comment]
Is there a way to find it?

**Comment by encounter** [comment]
Not without brute forcing a few quintillion hashes.

**Comment by simsdj** [comment]
And that’s probably something the average person can’t do?

**Comment by encounter** [comment]
Nope, unfortunately not

**Comment by simsdj** [comment]
So I should restore and update?

**Comment by nnvt** [comment]
I have blobs saved from the tss saver site, is there a chance that they are valid?

**Comment by encounter** [comment]
Blobs for A10X & A11 devices (iPhone 8/X, iPad Pro 2nd gen, Apple TV 4K) saved from TSS Saver before yesterday-ish are 100% invalid. See [here](https://www.reddit.com/r/jailbreak/comments/7n5aiu/update_tsssaver_has_been_updated_to_support/).

I've been working with the various SHSH-saver-tool owners to get this issue resolved for the future. Will release an updated futurerestore for A10X/A11 devices soon and include all the information there too. 

(To clarify: the updated futurerestore will still NOT work with invalid blobs; merely fixing unrelated issues)
