### ISSUE TITLE
ERROR: Unable to receive message from FDR 000000000404BAC0 (-4). 0/2 bytes

### ISSUE THREAD

**Issue by ClappyBird** [encounter/futurerestore#6]
Hi when i try to downgrade my iPhone 5s from iOS 11.1.2 to iOS 10.3.1 i have this error when i see a progression bar with apple logo... Can you help me please? Thanks in advance for your help.

**Comment by ClappyBird** [comment]
I use the windows version by the way and i have the shsh2 blobs for iOS 10.3.1.

**Comment by encounter** [comment]
Can you post a full log?

**Comment by ClappyBird** [comment]
Where can i find the log?

**Comment by ClappyBird** [comment]
C:\Users\HP-j\Downloads\Compressed\futurerestore_v161_windows>futurerestore -t
.shsh2 -b BB.bbfw -p OTA.plist -s sep.im4p -m OTA.plist -p OTA.plist -w 10.3.1
psw
Version: 15fcc8849c526d55f8bcfe4c18e20b27ac1cd62a - 161
Odysseus Support: no
[INFO] 64bit device detected
futurerestore init done
reading ticket 1.shsh2 done
Found device product iPhone6,1
Found device board n51ap
[TSSC] opening OTA.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[TSSC] opening OTA.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is DX3NFNNCFF9R
waiting for nonce: c6 e2 c7 d0 da 78 ba 06 44 c8 31 40 70 5f c0 07 ad 1a c4 a1
Got ApNonce from device: c6 e2 c7 d0 da 78 ba 06 44 c8 31 40 70 5f c0 07 ad 1a
4 a1
Device has requested ApNonce now
Found device in Recovery mode
Identified device as n51ap, iPhone6,1
Extracting BuildManifest from IPSW
Product Version: 10.3.1
Product Build: 14E304 Major: 14
Device supports Image4: true
Got APNonce from device: c6 e2 c7 d0 da 78 ba 06 44 c8 31 40 70 5f c0 07 ad 1a
4 a1
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Extracting filesystem from IPSW
Extracting iBEC.iphone6.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (648345 bytes)...
waiting for device to reconnect... .
Getting SepNonce in recovery mode... ec ba a3 0f 7e 6b bd 38 75 28 cd 50 72 e1
9 43 fc f8 39 f1
Getting ApNonce in recovery mode... c6 e2 c7 d0 da 78 ba 06 44 c8 31 40 70 5f
 07 ad 1a c4 a1
[WARNING] Setting bgcolor to green! If you don't see a green screen, then your
evice didn't boot iBEC correctly
Recovery Mode Environment:
iBoot build-version=iBoot-3406.50.244
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~iphone.s5l8960x.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (11640 bytes)...
ramdisk-size=0x10000000
Extracting 058-55512-168.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (41575446 bytes)...
Extracting DeviceTree.n51ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (107921 bytes)...
Extracting kernelcache.release.iphone6...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (12168007 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device...
Waiting for device...
Device 5724e7f09d2cb9fcc1b0a5cd845fbd94c46e8217 is now connected in restore mo
...
Connecting now...
Connected to com.apple.mobile.restored, version 14
Device 5724e7f09d2cb9fcc1b0a5cd845fbd94c46e8217 has successfully entered resto
 mode
Hardware Information:
BoardID: 0
ChipID: 35168
UniqueChipID: 8613709046704
ProductionMode: true
Starting FDR listener thread
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.iphone6.RELEASE.im4p...
Personalizing IMG4 component LLB...
Extracting applelogo@2x~iphone.s5l8960x.im4p...
Personalizing IMG4 component AppleLogo...
Extracting batterycharging0@2x~iphone.s5l8960x.im4p...
Personalizing IMG4 component BatteryCharging0...
Extracting batterycharging1@2x~iphone.s5l8960x.im4p...
Personalizing IMG4 component BatteryCharging1...
Extracting batteryfull@2x~iphone.s5l8960x.im4p...
Personalizing IMG4 component BatteryFull...
Extracting batterylow0@2x~iphone.s5l8960x.im4p...
Personalizing IMG4 component BatteryLow0...
Extracting batterylow1@2x~iphone.s5l8960x.im4p...
Personalizing IMG4 component BatteryLow1...
Extracting glyphplugin@1136~iphone-lightning.s5l8960x.im4p...
Personalizing IMG4 component BatteryPlugin...
Extracting DeviceTree.n51ap.im4p...
Personalizing IMG4 component DeviceTree...
Extracting recoverymode@1136~iphone-lightning.s5l8960x.im4p...
Personalizing IMG4 component RecoveryMode...
Extracting iBoot.iphone6.RELEASE.im4p...
Personalizing IMG4 component iBoot...
Not personalizing component RestoreSEP...
Not personalizing component SEP...
Sending NORData now...
Done sending NORData
ERROR: Unable to receive message from FDR 000000000400F440 (-4). 0/2 bytes

**Comment by ClappyBird** [comment]
The log:



C:\Users\HP-j\Downloads\Compressed\futurerestore_v161_windows>futurerestore
-t
.shsh2 -b BB.bbfw -p OTA.plist -s sep.im4p -m OTA.plist -p OTA.plist -w
10.3.1
psw
Version: 15fcc88
<https://github.com/encounter/futurerestore/commit/15fcc8849c526d55f8bcfe4c18e20b27ac1cd62a>
-
161
Odysseus Support: no
[INFO] 64bit device detected
futurerestore init done
reading ticket 1.shsh2 done
Found device product iPhone6,1
Found device board n51ap
[TSSC] opening OTA.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[TSSC] opening OTA.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is DX3NFNNCFF9R
waiting for nonce: c6 e2 c7 d0 da 78 ba 06 44 c8 31 40 70 5f c0 07 ad 1a c4
a1
Got ApNonce from device: c6 e2 c7 d0 da 78 ba 06 44 c8 31 40 70 5f c0 07 ad
1a
4 a1
Device has requested ApNonce now
Found device in Recovery mode
Identified device as n51ap, iPhone6,1
Extracting BuildManifest from IPSW
Product Version: 10.3.1
Product Build: 14E304 Major: 14
Device supports Image4: true
Got APNonce from device: c6 e2 c7 d0 da 78 ba 06 44 c8 31 40 70 5f c0 07 ad
1a
4 a1
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Extracting filesystem from IPSW
Extracting iBEC.iphone6.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (648345 bytes)...
waiting for device to reconnect... .
Getting SepNonce in recovery mode... ec ba a3 0f 7e 6b bd 38 75 28 cd 50 72
e1
9 43 fc f8 39 f1
Getting ApNonce in recovery mode... c6 e2 c7 d0 da 78 ba 06 44 c8 31 40 70
5f
07 ad 1a c4 a1
[WARNING] Setting bgcolor to green! If you don't see a green screen, then
your
evice didn't boot iBEC correctly
Recovery Mode Environment:
iBoot build-version=iBoot-3406.50.244
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2xiphone.s5l8960x.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (11640 bytes)...
ramdisk-size=0x10000000
Extracting 058-55512-168.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (41575446 bytes)...
Extracting DeviceTree.n51ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (107921 bytes)...
Extracting kernelcache.release.iphone6...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (12168007 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device...
Waiting for device...
Device 5724e7f09d2cb9fcc1b0a5cd845fbd94c46e8217 is now connected in restore
mo
...
Connecting now...
Connected to com.apple.mobile.restored, version 14
Device 5724e7f09d2cb9fcc1b0a5cd845fbd94c46e8217 has successfully entered
resto
mode
Hardware Information:
BoardID: 0
ChipID: 35168
UniqueChipID: 8613709046704
ProductionMode: true
Starting FDR listener thread
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.iphone6.RELEASE.im4p...
Personalizing IMG4 component LLB...
Extracting applelogo@2xiphone.s5l8960x.im4p...
Personalizing IMG4 component AppleLogo...
Extracting batterycharging0@2xiphone.s5l8960x.im4p...
Personalizing IMG4 component BatteryCharging0...
Extracting batterycharging1@2xiphone.s5l8960x.im4p...
Personalizing IMG4 component BatteryCharging1...
Extracting batteryfull@2xiphone.s5l8960x.im4p...
Personalizing IMG4 component BatteryFull...
Extracting batterylow0@2xiphone.s5l8960x.im4p...
Personalizing IMG4 component BatteryLow0...
Extracting batterylow1@2xiphone.s5l8960x.im4p...
Personalizing IMG4 component BatteryLow1...
Extracting glyphplugin@1136iphone-lightning.s5l8960x.im4p...
Personalizing IMG4 component BatteryPlugin...
Extracting DeviceTree.n51ap.im4p...
Personalizing IMG4 component DeviceTree...
Extracting recoverymode@1136~iphone-lightning.s5l8960x.im4p...
Personalizing IMG4 component RecoveryMode...
Extracting iBoot.iphone6.RELEASE.im4p...
Personalizing IMG4 component iBoot...
Not personalizing component RestoreSEP...
Not personalizing component SEP...
Sending NORData now...
Done sending NORData
ERROR: Unable to receive message from FDR 000000000400F440 (-4). 0/2 bytes

2017-12-29 21:06 GMT-05:00 Luke Street <notifications@github.com>:

**Comment by encounter** [comment]
Looks like for the n51ap, you need to use `Firmware/Mav7Mav8-7.51.00.Release.bbfw` for baseband and `Firmware/all_flash/sep-firmware.n51.RELEASE.im4p` for SEP. Are these the files you used?

**Comment by ClappyBird** [comment]
Yes

**Comment by ClappyBird** [comment]
Sep from the iOS 10.3.1 ipsw or the 10.3.3 ipsw?

**Comment by ClappyBird** [comment]
I also tried to downgrade to iOS 10.3.3 with shshs i have the same error, do you think it's from the iPhone?

**Comment by ClappyBird** [comment]
Now i have this error: ERROR: Unable to receive message from FDR 0000000003F1B200 (-4). 0/2 bytes

**Comment by ClappyBird** [comment]
I solved the problem it was the hosts file that prevented the downgrade. Thanks for your help.
